import { JsonRpcProvider, Wallet, Contract, type Log } from "ethers";
import { env } from "../config/env.js";
import type { TaskPayAbi } from "./types.js";
import abi from "./TaskPay.abi.json" with { type: "json" };

export const provider = new JsonRpcProvider(env.RPC_URL, env.CHAIN_ID, {
  staticNetwork: true, // pin to the configured chain; a wrong-RPC mixup should fail loud
});

export const oracleWallet = new Wallet(env.ORACLE_PRIVATE_KEY, provider);

// Typed contract: method names/arg shapes are checked against TaskPayAbi
// (generated by `forge inspect`/hand-maintained — see types.ts).
export const contract = new Contract(env.CONTRACT_ADDRESS, abi, oracleWallet) as unknown as TaskPayAbi;

// ABI-only instance bound to the provider (no wallet): safe for pure reads
// from the poller/scan without risking an accidental signed call.
export const rawContract = new Contract(env.CONTRACT_ADDRESS, abi, provider) as unknown as TaskPayAbi;

export interface TaskStruct {
  requester: string;
  agent: string;
  amount: bigint;
  specHash: string;
  submission: string;
  status: number;
  createdAt: bigint;
  acceptDeadline: bigint;
  workDeadline: bigint;
  reviewDeadline: bigint;
}

// queryFilter is not part of the typed method surface (TaskPayAbi covers only
// the methods the oracle calls); events.ts imports Log for its signature.
export type { Log };


export const Status = {
  Created: 0,
  Accepted: 1,
  Submitted: 2,
  Disputed: 3,
  PendingChallenge: 4,
  Challenged: 5,
  Released: 6,
  Refunded: 7,
  Cancelled: 8,
} as const;

export const AgentRole = {
  Reviewer: 0,
  FraudSanity: 1,
  Arbiter: 2,
} as const;
